apiVersion: v1
kind: Service
metadata: 
  name: patient-service
  app: patient-service
spec:
  type: LoadBalancer
  selector:
    app: patient-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
