variable "vpc_cidr" {}
variable "vpc_name" {}
variable "owner" {}
variable "environment" {}
variable "aws_region" {}
variable "azs" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "bucket_name" {}
variable "inbound_ports" {}
variable "outbound_ports" {}