name: "Terraform Manual Deployment"

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
    inputs:
      environment:
        description: "Select environment to deploy (dev/staging/prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  Terraform-Plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log into GH registry
        uses: actions/checkout@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TMP_PAT_TOKEN }}         

      - name: "Terraform Init"
        run: |
          terraform init
         # terraform workspace select ${{ inputs.environment }}
        

      - name: "Terraform Format Check"
        run: |
          terraform fmt -check

      - name: "Terraform Validate"
        run: |
          terraform validate

      - name: "Terraform Plan"
        run: |
          terraform plan --var-file="dev.tfvars"

  # approve:
  #   name: "Manual Approval for Production"
  #   if: inputs.environment == 'prod'  # Only require approval for production
  #   needs: Terraform-Plan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Wait for Manual Approval"
  #       uses: hmarr/auto-approve-action@v3
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}

  apply:
    name: "Terraform Apply"
    needs: Terraform-plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log into GH registry
        uses: actions/checkout@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TMP_PAT_TOKEN }}

      - name: "Terraform Apply"
        run: terraform apply --var-file="dev.tfvars" -auto-approve tfplan
